using Terraria.ModLoader;

using Terraria.ID;

namespace ApocalypseSupreme
{
	public class ApocalypseSupreme : Mod
	{public override void AddRecipes()
		{
			ModRecipe recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.LeadBar);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.IronBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.IronBar);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.LeadBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.CopperBar);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.TinBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.TinBar);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.CopperBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.SilverBar);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.TungstenBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.TungstenBar);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.SilverBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.GoldBar);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.PlatinumBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.PlatinumBar);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.GoldBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.CobaltBar);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.PalladiumBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.PalladiumBar);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.CobaltBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.MythrilBar);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.OrichalcumBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.OrichalcumBar);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.MythrilBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.AdamantiteBar);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.TitaniumBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.TitaniumBar);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.AdamantiteBar);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.LeadOre);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.IronOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.IronOre);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.LeadOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.CopperOre);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.TinOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.TinOre);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.CopperOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.SilverOre);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.TungstenOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.TungstenOre);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.SilverOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.GoldOre);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.PlatinumOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.PlatinumOre);
			recipe.AddTile(TileID.Furnaces);
			recipe.SetResult(ItemID.GoldOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.CobaltOre);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.PalladiumOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.PalladiumOre);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.CobaltOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.MythrilOre);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.OrichalcumOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.OrichalcumOre);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.MythrilOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.AdamantiteOre);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.TitaniumOre);
			recipe.AddRecipe();
			recipe = new ModRecipe(this);
			recipe.AddIngredient(ItemID.TitaniumOre);
			recipe.AddTile(TileID.AdamantiteForge);
			recipe.SetResult(ItemID.AdamantiteOre);
			recipe.AddRecipe();
		}
	}
}
